import { NextResponse } from 'next/server';
import YAML from 'yaml';
import { parseProjectSpec } from '@/lib/spec';

export const runtime = 'nodejs';

/**
 * Builds a QA definition from the wizard form.
 *
 * The document is assembled with a real YAML serializer rather than string
 * concatenation, so a name containing a quote, colon or newline cannot produce a
 * broken — or injected — definition. The result is parsed back before returning
 * so the wizard can never hand out a file that fails to import.
 */
export async function POST(req: Request) {
  try {
    const b = await req.json();
    const accounts = Array.isArray(b.accounts) ? b.accounts : [];

    const config: Record<string, unknown> = {
      version: 1,
      ...(b.projectId ? { projectId: String(b.projectId) } : {}),
      system: {
        name: String(b.name || 'My System'),
        ...(b.description ? { description: String(b.description) } : {}),
      },
      environments: [{
        id: String(b.envId || 'qa'),
        label: String(b.envLabel || 'QA'),
        kind: String(b.kind || 'qa'),
        ...(b.apiBaseUrl ? { apiBaseUrl: String(b.apiBaseUrl) } : {}),
        ...(b.openapiUrl ? { openapiUrl: String(b.openapiUrl) } : {}),
        webApps: b.webUrl ? [{ id: 'main', label: String(b.webAppLabel || 'Main Web App'), url: String(b.webUrl) }] : [],
        ...(b.catalogUrl
          ? {
              accountCatalog: {
                url: String(b.catalogUrl),
                ...(b.requiredRoles ? { requiredRoles: String(b.requiredRoles).split(',').map((s: string) => s.trim()).filter(Boolean) } : {}),
              },
            }
          : {}),
      }],
      accounts: accounts
        .filter((a: any) => a && (a.identifier || a.password || a.role))
        .map((a: any, i: number) => ({
          id: String(a.id || `account-${i + 1}`),
          role: String(a.role || 'unknown'),
          ...(a.label ? { label: String(a.label) } : {}),
          loginType: String(a.loginType || 'email_password'),
          credentials: {
            ...(a.identifier ? { identifier: String(a.identifier) } : {}),
            ...(a.password ? { password: String(a.password) } : {}),
          },
        })),
      qa: {
        preferredLanguage: String(b.preferredLanguage || 'en'),
        destructiveActions: String(b.destructiveActions || 'allow-build-test-only'),
      },
    };

    const yaml = YAML.stringify(config, { lineWidth: 0 }).trimEnd();
    const raw = `# QA System Specification\n\nGenerated by the onboarding wizard. Review the values, then import it.\n\n\`\`\`qa-config\n${yaml}\n\`\`\`\n`;

    // Fail here rather than at import time.
    let warning: string | undefined;
    try { parseProjectSpec(raw); } catch (e) { warning = e instanceof Error ? e.message : String(e); }

    return NextResponse.json({ raw, warning });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : String(e) }, { status: 400 });
  }
}
